export const ZIP_CODE_VALIDATION_REQUEST = "ZIP_CODE_VALIDATION_REQUEST";
export const ZIP_CODE_VALIDATION_SUCCESS = "ZIP_CODE_VALIDATION_SUCCESS";
export const ZIP_CODE_VALIDATION_FAILURE = "ZIP_CODE_VALIDATION_FAILURE";